package model.User;

import java.sql.Date;

public class BusinessOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.id
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.business_no
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private String businessNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.name
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.order_info
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private String orderInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.order_price
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private Integer orderPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.CREATE_TIME
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.STATUS
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_order.PAY_TYPE
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	private Integer payType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.id
	 * @return  the value of business_order.id
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.id
	 * @param id  the value for business_order.id
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.business_no
	 * @return  the value of business_order.business_no
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public String getBusinessNo() {
		return businessNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.business_no
	 * @param businessNo  the value for business_order.business_no
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setBusinessNo(String businessNo) {
		this.businessNo = businessNo == null ? null : businessNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.name
	 * @return  the value of business_order.name
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.name
	 * @param name  the value for business_order.name
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.order_info
	 * @return  the value of business_order.order_info
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public String getOrderInfo() {
		return orderInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.order_info
	 * @param orderInfo  the value for business_order.order_info
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setOrderInfo(String order_Info) {
		this.orderInfo = order_Info == null ? null : order_Info.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.order_price
	 * @return  the value of business_order.order_price
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.CREATE_TIME
	 * @return  the value of business_order.CREATE_TIME
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	public Integer getOrderPrice() {
		return orderPrice;
	}

	public void setOrderPrice(Integer orderPrice) {
		this.orderPrice = orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.CREATE_TIME
	 * @param createTime  the value for business_order.CREATE_TIME
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.STATUS
	 * @return  the value of business_order.STATUS
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.STATUS
	 * @param status  the value for business_order.STATUS
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_order.PAY_TYPE
	 * @return  the value of business_order.PAY_TYPE
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_order.PAY_TYPE
	 * @param payType  the value for business_order.PAY_TYPE
	 * @mbg.generated  Mon Nov 04 09:46:51 GMT+08:00 2019
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}
}